name: Run Rest Assured Test Cases

on:
  push:
    branches: ["master"]


jobs:
  test:
    runs-on: macos-latest
    steps:
<<<<<<< HEAD
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
       with:
         distribution: 'temurin'
          cache: maven
    - run: mvn clean test
=======
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v3
        - with:
            java-version: "11"
            distribution: 'temurin'
            cache: maven
        - run: mvn clean test
>>>>>>> bc5c0d834dae0d3cb0e15f496d931a701f711ee8
