name: Run Rest Assured Test Cases

on:
  push:
    branches: ["master"]


jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
       with:
         distribution: 'temurin'
          cache: maven
    - run: mvn clean test
